"""empty message

Revision ID: 749fe8ef3cbf
Revises: 
Create Date: 2021-04-20 12:17:20.110864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749fe8ef3cbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athleteNotifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('athleteNotifications')
    # ### end Alembic commands ###
